version: '3'
services:
  redis:
    image: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    env_file:
      - .env
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./redis/data:/data

  redis-commander:
    container_name: redis-commander-crm
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASS}
    ports:
      - '127.0.0.1:8081:8081'